version: "3.9"
services:
  bot:
    build: .
    container_name: fishdex_bot
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: fishdex_postgres  
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
